/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xtulator_android_XTulatorActivity */

#ifndef _Included_com_xtulator_android_XTulatorActivity
#define _Included_com_xtulator_android_XTulatorActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xtulator_android_XTulatorActivity_nativeInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeRun
  (JNIEnv *, jobject);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeKeyDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeKeyUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeMouseEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeMouseEvent
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativePause
  (JNIEnv *, jobject);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeResume
  (JNIEnv *, jobject);

/*
 * Class:     com_xtulator_android_XTulatorActivity
 * Method:    nativeReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtulator_android_XTulatorActivity_nativeReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif